### ISSUE TITLE
HttpProvider Missing

### ISSUE THREAD

**Issue by Khazrak** [anaplaninc/anaplan-mulesoft#23]
I get the error:
INFO  2015-03-23 16:07:02,958 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: class com.anaplan.connector.connectivity.CertAuthConnectionStrategyAnaplanConnectorAdapter Initiating certificate connection...
INFO  2015-03-23 16:07:02,961 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] Stored connection properties!
INFO  2015-03-23 16:07:02,962 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] Establishing connection....
INFO  2015-03-23 16:07:02,962 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] No new connection found, establishing new connection!
WARN  2015-03-23 16:07:02,962 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] API Url: https://api.anaplan.com/
INFO  2015-03-23 16:07:02,968 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] Certificate VALID!
INFO  2015-03-23 16:07:03,038 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] Connection closed.
**FATAL 2015-03-23 16:07:03,038 [[customertoanaplan].FileToAnaplanId.stage1.02] com.anaplan.connector.utils.LogUtil: [https://api.anaplan.com/] [null] No transport providers available; check the classpath contains the necessary libraries**

I have all the libraries for the Anaplan Connect-jar (should not need it).

A possible problem I used to have when I was using the Anaplan Connects (java-client)s source files was that the **HttpProvider.properties** was in the source folder:
anaplan-java-client/java/src/com/anaplan/client/transport/HttpProvider.properties

I should be in src/resources or Maven will not add it on packeing. If this is the case the source-code needs to be change to accommodate for the moved file (the source code links this directly).

**Comment by shuvozula** [comment]
This error almost seems like a ESB issue. Usually when its complaining about a missing transport, its the underlying ESB that is throwing this error, that gets bubbled up to the connector. Could you create a new flow and try it again? Its annoying I know, but sometimes the Configuration XML for the flow gets auto-generated incorrectly, happened a lot to me and I got similar errors like this. Unless you know the XML config well, I'd suggest creating a new flow. I've been unsuccessful in reproducing this issue, partly because Mulesoft just released ESB 3.6.1 which does not work well with the existing Devkit plugin for running connectors, so I'm stuck until they fix the bug on their end. ESB 3.6.0 is not available for download from their update site, which was used for building the connector. This happened when I updated my Studio to the latest and hence all the snafu.

Since this is a Maven project, we should not be including dependency jars or any other resources directly to the project, maven takes care of managing it via the <dependency> xml block and downloading them from the nexus repository when the connector is installed (check the pom.xml file).
