### ISSUE TITLE
Import operation adds header row as "data"

### ISSUE THREAD

**Issue by sagar-appnovation** [anaplaninc/anaplan-mulesoft#60]
When I tried to use "import" operation and provided CSV file contents as payload, I noticed that header row is duplicated and added as data as well. At line number 198 of AnaplanImportOperation.java class adds header row and for loop at line 202 loops the CSV data. At line 198 the header was added and since the for loop is running from 0th element, even the header row is added as data.

Line 198 : dataWriter.writeHeaderRow(rows.get(0));

Line 202:
for (String[] row : rows) {
     dataWriter.writeDataRow(row);
     ++rowsProcessed;
}

Proposed Fix at Line 202: 
for (String[] row : rows.subList(1, rows.size())) {
     dataWriter.writeDataRow(row);
     ++rowsProcessed;
}

**Comment by shuvozula** [comment]
Thank you for the feedback. We have this tracked as a bug and working towards applying the fix. Once QA has performed regression, we will mark it for the next release.

**Comment by sagar-appnovation** [comment]
Thanks for the update. Do you know planned release date of v1.1.4?

**Comment by shuvozula** [comment]
Quite soon, we haven’t set a date yet because we have to update Mulesoft also after the patch is applied to master. So it depends on their release cycle as well, which could take a few weeks. 

But if you’re interested in test-driving it right now, check out the ‘develop’ branch from the repository and install it from source in Anypoint studio. You might have to uninstall it later and install the published connector from Mulesoft repos, so that you can continue receiving new updates from us.
