### ISSUE TITLE
Unable to return Detailed Error FIle after import

### ISSUE THREAD

**Issue by JWihtol** [anaplaninc/anaplan-mulesoft#62]
Issue: Anaplan Connector throws Null Pointer Exception while returning "Import" response in case the data upload is partially successful

Observations:
1. When "Import" operation of an Anaplan Connector 1.1.3 is invoked and the data is imported successfully in Anaplan without any errors or warnings, then Anaplan Connector returns response like below:

Sample Success Response:

Import ran successfully: 
Date cells: 122
Type cells: 122
Document Number cells: 122
Name cells: 45
Account cells: 122
Memo cells: 113
Amount (LC) cells: 122
Department cells: 122
Subsidiary cells: 122
Account Type cells: 122
RPM ID cells: 17
Employee ID cells: 76
Employee Name cells: 76Import completed successfully: (122 records processed)

2. When "Import" operation of an Anaplan Connector 1.1.3 is invoked and there is some problem while importing the records, then Anaplan Connector should return valid response with detailed information about which records failed any why, but Anaplan Connector throws Null Pointer Exception. So, it is now hard for us to identify which record failed any why. Please find attached error log for this issue. I have also attached sample csv file generated from code. Please note that for testing purpose generated CSV has invalid Account.

I also tried to upload a sample CSV file (with invalid Account) manually using Anaplan for testing purpose. Please see result screenshots below.

It will be really great if we can get some help to fix Anaplan Connector so that valid error response is returned, then we can use that response for sent email notifications with failed records and reason for failure.

![import results in anaplan](https://cloud.githubusercontent.com/assets/18199681/14193072/bc007688-f756-11e5-831e-e84ba5f71778.png)
![import details in anaplan](https://cloud.githubusercontent.com/assets/18199681/14193076/c01677ae-f756-11e5-8d2a-17380849f080.png)

[Error_Logs(1).txt](https://github.com/anaplaninc/anaplan-mulesoft/files/198701/Error_Logs.1.txt)

**Comment by JWihtol** [comment]
[Sample_Incorrect_Data(2).xlsx](https://github.com/anaplaninc/anaplan-mulesoft/files/198705/Sample_Incorrect_Data.2.xlsx)

**Comment by shuvozula** [comment]
Could you also provide the correct Sample Data Xlsx file as well, so that we can recreate the issue? Thanks.

**Comment by JWihtol** [comment]
Hi Shuvo,
Please see attached file.

Thanks,
John

[Sample_Incorrect_Data(3).xlsx](https://github.com/anaplaninc/anaplan-mulesoft/files/198845/Sample_Incorrect_Data.3.xlsx)

**Comment by shuvozula** [comment]
Hi John,

We have a fix for this issue and we're in the process of QA validation/verification for release with v1.1.4. After that, we will have to complete the re-certification process with Mulesoft to get it released in their marketplace. So, we don't have an exact date for when it will be available there, partly due to their own release timeline and re-certification criteria. But usually it takes a couple of weeks, maybe sooner.

In the meantime, if you wish to test-drive this fix, feel free to checkout the "bug/INTEGRA-915" branch from this repo and then import the connector as a connector project into Anypoint Studio. After that, install the connector from source and you are set to test-drive the fix. Just make sure that the Mule-flow Project points to the newly installed connector and not the pre-installed one (check Configure build path -> Libraries tab). Otherwise, I would recommend to wait until Mulesoft releases it in their market-place.

Thanks,
Spondon.

**Comment by JWihtol** [comment]
Thanks Spondon! That's great to hear!

I think we will take a shot at test driving this with the branch that you
added.

John

[image: http://www.twelvecg.com/] <http://www.twelvecg.com/>

*John Wihtol *| Partner
John@twelvecg.com
m: (916) 215-8668 <916-215-8668>
skype: john.wihtol | twitter: @johnwihtol <https://twitter.com/johnwihtol>
website <http://www.twelvecg.com/> | twitter <https://twitter.com/twelvecg>

**Comment by shuvozula** [comment]
Hi John,

Mulesoft just released v1.1.4 of the Mulesoft connector at their marketplace. Please go ahead and update your connector from Anypoint studio to get the latest fixes and updates.

Thanks,
Spondon.

**Comment by JWihtol** [comment]
Thanks Spondon, will do!

[image: http://www.twelvecg.com/] <http://www.twelvecg.com/>

*John Wihtol *| Partner
John@twelvecg.com
m: (916) 215-8668 <916-215-8668>
skype: john.wihtol | twitter: @johnwihtol <https://twitter.com/johnwihtol>
website <http://www.twelvecg.com/> | twitter <https://twitter.com/twelvecg>
